### ISSUE TITLE
Sync Progress Bubbles

### ISSUE THREAD

**Issue by ErikSin** [digidem/mapeo-mobile-shell#17]
# Sync Progress Bubbles
Update : Bubbles can remain static. The below path is only if we have time.

**
The bubbles should track the sync progress between this device and other sync participants. The fill of the bubble should track the progress.

<img width="292" alt="image" src="https://user-images.githubusercontent.com/67773827/229608313-4358605f-b825-48e3-a46f-403b0050c2ae.png">

## To Do:
- [ ] Create bubbles using [React Native Skia](https://github.com/Shopify/react-native-skia)
- [ ] Animate bubbles using Skia
- [ ] Progress for each bubble should come from [`useIndividualSync`](https://github.com/digidem/mapeo-mobile-shell/blob/3a50502d70fee425aa4119c6dbf87e5454a1147f/src/hooks/stores/useSyncStore.ts#L88)
- [ ] The list of all active syncs will be hardcoded, and should come from the parent. See [Sync Screen with Devices](https://github.com/digidem/mapeo-mobile-shell/issues/12)
- [ ] `OnClick` of each bubble should open a bottom sheet. Do not create the bottom sheet, but include the logic to open the bottom sheet
- [ ] Bubbles are randomly sized
- [ ] Bubbles are placed on screen randomly (or should look random) using [d3](https://d3js.org/). Bubbles do not need to move.

**Comment by ximenabb** [comment]
Discussed with @achou11 , de-prioritizing this ticket since the bubbles animation is not the top priority of the shell app.

**Comment by achou11** [comment]
For posterity, code that was addressing this lives in https://github.com/digidem/mapeo-mobile-shell/tree/17/sync-bubbles
